version: 2
jobs:
  test:
    docker:
    - image: circleci/buildpack-deps:14.04-browsers
    steps:
    - checkout
    - run: java -version
    - run: sudo apt-get install maven
    - run: mvn clean test site
    - store_artifacts:
        path: target/surefire-reports
        destination: tr1
    - run:
              name: Save test results
              command: |
                mkdir -p ~/junit/
                find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
              when: always
          - store_test_results:
              path: ~/junit
          - store_artifacts:
              path: ~/junit
workflows:
  version: 2
  build_and_test:
    jobs:
    - test